---
- name: ensure PM2 is installed
  npm:
    name=pm2
    version=latest
    global=yes
    state=present

- name: ensure PM2 got service file
  command: pm2 startup linux -u node --hp /home/node

- name: ensure PM2 service is on
  service:
    name=pm2-init.sh
    enabled=yes
