---

- name: Add nodesource keys
  apt_key:
    url="https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state=present

- name: Add nodesource apt sources list deb
  apt_repository:
    repo="deb https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main"
    state=present

- name: Add nodesource apt sources list deb src
  apt_repository:
    repo="deb-src https://deb.nodesource.com/node_4.x {{ ansible_distribution_release }} main"
    state=present

- name: Install nodejs
  apt: pkg=nodejs state=latest update_cache=true


- name: allow low port binding
  command: setcap cap_net_bind_service=+ep /usr/bin/nodejs

- name: Create server directory
  file: path=/srv state=directory owner=node group=node mode=0770

- name: jump to latest npm
  npm:
    name=npm
    version=latest
    global=yes
    state=present
